name: Docker Image CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag laurentgrangeau/devoxx-ma:$GITHUB_SHA
    - name: Login to Dockerhub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.docker_username }}
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
    - name: Push the Docker image
      run: docker push laurentgrangeau/devoxx-ma:$GITHUB_SHA
